### ISSUE TITLE
drawing breakpoint annotations is broken over text editor

### ISSUE THREAD

**Issue by fzwo** [fzwo/FRMBreakFast#1]
If you set your font to a huge size, breakpoint annotations will grow accordingly, and their point will be outside the sidebar view. It then renders normally, that is, without our special treatment.

![screenshot](https://cloud.githubusercontent.com/assets/979197/10728088/427f0218-7bdf-11e5-803c-6bb3e98bd0ac.png)

**Comment by mgmart** [comment]
You will see this also if you're switching off the 'code folding ribbon'
<img width="90" alt="trackextension_swift" src="https://cloud.githubusercontent.com/assets/3919652/10765095/8829a208-7cd1-11e5-84f9-b36aace95773.png">

**Comment by fzwo** [comment]
Thanks for letting me know! I'm starting to think I'll have to revisit drawing. `DBGBreakpointAnnotation` looks like an interesting starting point, with its `_icon` iVar, `_iconForRect:` and `drawSidebarMarkerIconInRect:textView:` methods.
