### ISSUE TITLE
Breakpoint navigator does not have special icons

### ISSUE THREAD

**Issue by fzwo** [fzwo/FRMBreakFast#3]
Would be nice to also give special icons to breakpoints with actions or non-halting breakpoints also in the manager.

**CAUTION:** Apple has apparently changed implementation of that manager between Xcode 6 and 7. Please be aware of that when tackling this issue.

**Comment by sjmills** [comment]
This would be really, really helpful. I've actually submitted a feature request to Apple for this. I can't guess how many times I've had to inspect each and every breakpoint in a large project to find the one that's spitting out something generic like "1" or whatever. Being able to see at a glance which breakpoints have an action assigned or are continuing would be an enormous time saver.
