### ISSUE TITLE
Test with Xcode 7.1 and add UUID

### ISSUE THREAD

**Issue by fzwo** [fzwo/FRMBreakFast#6]

**Comment by mgmart** [comment]
Works fine for me.

Is it correct that DVTPlugInCompatibilityUUID is unique for every Xcode version and not every installation?

7265231C-39B4-402C-89E1-16167C4CC990

Version 7.1 (7B91b)

**Comment by fzwo** [comment]
Added in c8fb861339f193205748fbb9433f2b6769ed8258. Thank you for the heads-up!

Yes, Xcode compatibility UUIDs are unique per build, not per installation.
